// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hffrmcptjzuqrcogciei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmZnJtY3B0anp1cXJjb2djaWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODExNDYsImV4cCI6MjA2NTA1NzE0Nn0.VeFpRUKpqlXiJUeLEvUerp20dGXL2aHUY6sLizaen_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);